
#+TITLE:     Course Reflection
#+AUTHOR:    Jacob Håkansson
#+EMAIL:     jacobhak@kth.se
#+DATE:      2014-03-21 Fri
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:
I've really enjoyed the course. The topic (the future) was really
appealing to me, It's something that like to think about, although somewhat
casually. The course gave me the opportunity explore it in a more
serious manner, while combining it with lessons in design. That felt
really ingenious to me, the practicality of combining the teaching of
design methodologies with an underlying progressing
project/subject. The theory wouldn't have been as interesting without
the context, experimentation and discussion.

I'm still not sure whether I would have wanted to produce more
material. That's something that I wanted to do more throughout the
course, although in retrospect I think the time spent on exploration
was very important for the final work. That's one of the key lessons
of the course I think, that there is more to interaction design than
meets the eye, quite literally!

As for the group work, we had a lot of problems with illness. I was
out for two weeks, everyone missed something, some people more
than others. But when we worked together we were really effective and
had many great discussions. Everyone contributed. For the final work
Deborah and I created the visuals for the interface, Deborah did most
of the Photoshoping, and I built the demo app. Everyone contributed
to the video, I did the writing, presentation and voice-over.
I also did the audio editing.

In the report I contributed with an abstract (it was modified later), one paragraph
in each of the introduction and exploration sections, one subsection in the
related work section, and the whole discussion section. Everyone
contributed with editing, deciding what to remove and what to include.

I enjoyed the giving and taking of critique, the weekly feedback from
the teachers was very important. I'm very critical both when it comes
to myself and other people's work, so I was relatively talkative
during the critique sessions. I hope I contributed with some valuable
ideas to the other groups, as they most certainly inspired me. Again,
the teachers were very inspirational and constructive. I was in
Ylva's group so that's more aimed at her than the others (for obvious
reasons).

I've learnt that KTH Social is not a very good tool. I would wanted
the actual deliverables and assignments separate from (but connected
to) the calendar. Maybe the teachers can create a more condensed
document or page describing what should be done. The deadlines was
sometimes hard to find. I for one had totally forgotten about this
reflection text :)

Thank you for a good course!
