#+TITLE:     Interaction design methods reflection
#+AUTHOR:    Jacob Håkansson
#+EMAIL:     jacobhak@kth.se
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:nil timestamp:nil
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

I was a part of the project group which made Flagtastic. Flagtastic
is a system with which you can communicate your wishes on the beach
using flags. The flags were put on a parasol and color coded
according to what you wanted to communicate. Red for activity, blue
for drinks, and yellow for food. When you raise a flag the parasol
syncs that state with the companion app, which also allows you to
specify what you want with a text message. The whole concept was conceived
as "flag-first" which would promote people talking with eachother
instead of just using their phone. The app was added to enhance the
experience, without being the full experience. In fact, you could use
the parasol alone, but using the app makes it easier to find people
if they aren't already close to you.

During the project everyone in the group worked together as well
as using a parallell design strategy. I was particularly responsible
for the initial graphical design of the app, and converting it to a
more interactive version. The final interactive prototype of the app
was made by Carl-Arvid, based on our previous work. I was also in
charge of most of the video production, although everyone was
involved in creating the storyboard, script and recording. I did the
post-production and voice-over, with the help of the other group
members' feedback.

I think the hardest part of the project was really the decision to
abandon our initial idea. The initial idea was conceived during the
ideation session, in which we brainstormed using post-its to combine
different ideas. We also evaluated the ideas using the 6 hats
thinking system. The decision was hard to make because I really liked
our initial idea and we had already put a couple of weeks worth of
work into it. However, the feedback we had gotten so far indicated
that we should rethink. It took some time to flesh out the new
concept, but we really got a lot of good feedback from the critique
sessions which put us on the final path. The critique sessions mainly
helped us to find "bugs" in our design, things that could be
misinterpreted or undesirable. But some of the critique also led to
us expanding the use of the parasol with the app and consider making
the parasol more of a digital hub on the beach. The final design
would probably be something different than it became if we didn't have
the critique sessions. It would be worse.

I would most likely use the techniques taught in the course outside
of school. Maybe not all of them, but I really liked the flow from
ideation to rapid prototyping with sketches and early feedback. That
rooted out problems with the design so we could refine it. If I was
working with other designers in a team (like in the course) parallell
prototyping would definitely be a part of the process. I liked the
mood boards for inspiration. The most valuable part was the feedback
from both potential users and other designers. The other designers
group might not be as easy to get feedback from in a different
situation. I might not have other designers around me. I think you
can make do with anyone that's opinionated about design, but the
feedback might vary in quality or focus. I think the most important
part is to get new ideas for the design or finding problems with the
design.

As you might expect, the one thing I liked most about the course was the
critique sessions. I like getting feedback and I like giving it. I
feel like the critique sessions were when you actually grew as a
designer. Sure, you had done the work to get there, but the sessions
gave you the opportunity to reflect, not just on your own design, but
others as well. I really liked the progression of topics and methods
throughout the course, it felt natural.

I think the film-making themed day was a little too much. The lecture
was overly technical, and frankly too long. The storyboarding session
was also too long, it could have been cut in half and let us do a
whole-class feedback session instead of us reworking the storyboards
before we got any real feedback. Maybe it was more valuable to other
groups, but pretty much all of our group members had the same idea on
how the video would play out. I did, however, like the individual
feedback sessions on the video, but they shouldn't have been during
exam-weeks.

The theme was fine. Other themes would have different constraints
that would impact the projects as well. I don't think it made
the work worse, but I don't think it made it better
either. Personally, I had hard time relating to the beach in general,
and specifically using technology on the beach. I do think there were
some brilliant projects in course which wouldn't had come out of
another topic, the Floafa and the underwater photobooth.
